apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-init
  namespace: kafka-platform
  labels:
    app: kafka-topic-init
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: kafka-topic-init
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-topics
          image: kafka-init-job:1.0.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: topic-init-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
